import localFont from "next/font/local";
import "./globals.css";
import NavBar from "./component/NavBar";
import Footer from "./component/Footer";
import { StoreProvider } from "./store/StoreProvider";
import logo from '@/public/logo.svg'

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "FOOD-X",
  description: "Generated by create next app",
  // icons :{
  //   icon: './favicon.jpg',
  //   apple: './favicon.jpg'
  // }
};

export default function RootLayout({ children }) {
  return (
    <StoreProvider>
      <html lang="en">
        
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased bg-amber-500 `}
        >
          <NavBar />

          {children}
          <Footer />
        </body>
      </html>
    </StoreProvider>
  );
}
